{
    "name": "Atlaxchange – Trade & Treasury (FX & Liquidity)",
    "version": "16.0.1.0.0",
    "summary": "Compute & manage company FX business rates from multiple liquidity sources",
    "author": "Novus Solutions",
    "category": "Customization",
    "depends": ["base", "mail", "account", "atlaxchange_app"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/fx_rate_sequence.xml",
        "views/fx_rate_views.xml",
        "views/allocate_transactions_wizard_views.xml",
        "views/treasury_stock_views.xml",
        "views/treasury_allocation_views.xml",
        "views/treasury_daily_batch_views.xml",
        "views/menu_views.xml",
    ],
    "demo": [],
    "application": True,
    "license": "LGPL-3",
}
