{
    "name": "Atlaxchange Ledger",
    "version": "16.0.1.0.0",
    "summary": "Manage Atlaxchange Client Transaction History",
    "category": "Custom",
    "author": "Novus Solutions",
    "website": "https://novussolutionsltd.com",
    "images": ["static/description/atlax_icon.png"],
    "license": "LGPL-3",
    "depends": ["base", "fetch_users_api", "contacts", "atlaxchange_app"],
    "data": [
        "security/ir.model.access.csv",
        "data/cron_job.xml",
        "views/ledger_views.xml",
        "views/account_statement_wizard_view.xml",
        "reports/account_statement_template.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "atlaxchange_ledger/static/src/js/ledger_client_action.js",
            "atlaxchange_ledger/static/src/xml/ledger_client_action.xml",
            'atlaxchange_ledger/static/src/components/ledger_dashboard.xml',
            'atlaxchange_ledger/static/src/components/LedgerDashboard.js',
            'atlaxchange_ledger/static/src/ledger_dashboard.js',
            'atlaxchange_ledger/static/src/js/ledger_refresh_button.js',
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
