{
    "name": "Atlax Wallet Accounting Sync",
    "version": "16.0.1.0.0",
    "summary": "Synchronize mirrored wallet transactions into draft journal entries for review",
    "category": "Accounting",
    "author": "Novus Solutions",
    "license": "LGPL-3",
    "depends": [
        "base",
        "account",
        "account_reports",
        "atlaxchange_app",
        "atlaxchange_ledger",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/account_move_wallet_sync_views.xml",
        "views/atlax_account_report_templates.xml",
        "views/atlax_account_report_definitions.xml",
        "views/custom_account_report_views.xml",
        "views/wallet_operational_report_views.xml",
        "views/wallet_conversion_rate_report_views.xml",
        "views/wallet_account_map_views.xml",
        "views/wallet_accounting_posting_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": False,
}
